version: 2.1

jobs:
  build:
    docker:
      - image: tinygo/tinygo-dev
    working_directory: /usr/local/go/src/github.com/tinygo-org/bluetooth
    steps:
      - checkout
      - run: tinygo version
      - run:
          name: "Run unit tests"
          command: go test
      - run:
          name: "Run TinyGo smoke tests"
          command: make smoketest-tinygo
      - run:
          name: "Run Linux smoke tests"
          command: make smoketest-linux
      - run:
          name: "Install Windows cross compiler"
          command: |
            # Install the tools themselves.
            apt-get install -y gcc-mingw-w64-x86-64
      - run:
          name: "Run Windows smoke tests"
          command: make smoketest-windows
  build-macos:
    macos:
      xcode: "10.3.0"
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            curl https://dl.google.com/go/go1.15.14.darwin-amd64.tar.gz -o go1.15.14.darwin-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.15.14.darwin-amd64.tar.gz
            ln -s /usr/local/go/bin/go /usr/local/bin/go
      - run: go version
      - run:
          name: "Run macOS smoke tests"
          command: make smoketest-macos

workflows:
  test-all:
    jobs:
      - build
      - build-macos
